deployments:
  registry-test:
    subdomain_port_mapping:
      - nginx:3000
    docker_registry:
      - server: r.cfcr.io 
        username: wisedrette
        password: $REGISTRY_PASSWORD
      - server: cloud.canister.io:5000
        username: wisedrette
        password: $REGISTRY_PASSWORD_CANISTER
